site_name: CrowdVision

markdown_extensions:
  - admonition

theme:
  name: material

nav:
  - Home: index.md
  - Requirements: requirements.md
  - Design: design.md
  - Data models: data.md
  - Architecture: architecture.md
  - Future roadmap & Integrations: future.md