name: twin-service-ci

on:
  push:
    branches: [master]
    paths:
      - "./server/twin-service/**"
  pull_request:
    branches: [master]
    paths:
      - "./server/twin-service/**"
jobs:
  twin-service:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server/twin-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x

      - name: ğŸ“¦ Install dependencies
        run: npm ci

      - name: ğŸ—ï¸ Build
        run: npm run build

      - name: ğŸ§ª Run Server Tests
        run: npm run test
        continue-on-error: false
